export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_TEACHERS = "GET_TEACHERS";
export const GET_TEACHER = "GET_TEACHER";
export const POST_TEACHER = "POST_TEACHER";
export const PUT_TEACHER = "PUT_TEACHER";

export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENT = "GET_STUDENT";
export const POST_STUDENT = "POST_STUDENT";
export const PUT_STUDENT = "PUT_STUDENT";

export const GET_SECTIONS = "GET_SECTIONS";
export const DELETE_SECTION = "DELETE_SECTION";

export const GET_CLASSSECTIONS = "GET_CLASSSECTIONS";
export const POST_CLASSSECTION = "POST_CLASSSECTION";
export const GET_CLASSSECTION = "GET_CLASSSECTION";
export const PUT_CLASSSECTIONS = "PUT_CLASSSECTIONS";
